### ISSUE TITLE
wkhtmltopdf execution failure

### ISSUE THREAD

**Issue by prantabiswas** [lang-ai/react-pdfs#1]
When I try to run the command: node example/invoice.js, I get this error:

```
{ Error: Command failed: wkhtmltopdf -B 0 -T 0 -L 0 -R 0 D:\4-11-2018 react-pdfs\react-pdfs\build\invoice.html D:\4-11-2018 react-pdfs\react-pdfs\build\invoice.pdf
'wkhtmltopdf' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:273:12)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
killed: false,
code: 1,
signal: null,
cmd: 'wkhtmltopdf -B 0 -T 0 -L 0 -R 0 D:\\4-11-2018 react-pdfs\\react-pdfs\\build\\invoice.html D:\\4-11-2018 react-pdfs\\react-pdfs\\build\\invoice.pdf' }
```

How to overcome this issue?

**Comment by albertorestifo** [comment]
Did you install the `wkhtmltopdf` tool?

You can see the installation instructions on [their website](https://wkhtmltopdf.org/). It's also available on homebrew in case you're on macOS
